(() => {
"use strict";
const VERSION="2.4.2",KEY="volleyball-trainer-v2-2",TEST_PASSWORD="";
const ownRoster=[{id:"a1",base:1,team:"own"},{id:"z1",base:2,team:"own"},{id:"m1",base:3,team:"own"},{id:"a2",base:4,team:"own"},{id:"z2",base:5,team:"own"},{id:"m2",base:6,team:"own"}];
const defaultRoles={a1:"AA",z1:"Z",m1:"MB",a2:"AA",z2:"Z",m2:"MB"};
const opponentRoster=[{id:"oa1",role:"AA",base:1,team:"opponent"},{id:"oz1",role:"Z",base:2,team:"opponent"},{id:"om1",role:"MB",base:3,team:"opponent"},{id:"oa2",role:"AA",base:4,team:"opponent"},{id:"oz2",role:"Z",base:5,team:"opponent"},{id:"om2",role:"MB",base:6,team:"opponent"}];
const allPlayers=[...ownRoster,...opponentRoster];
const ownSlots={1:{x:520,y:735},2:{x:520,y:545},3:{x:350,y:545},4:{x:180,y:545},5:{x:180,y:735},6:{x:350,y:735}};
const opponentSlots={1:{x:180,y:165},2:{x:180,y:355},3:{x:350,y:355},4:{x:520,y:355},5:{x:520,y:165},6:{x:350,y:165}};
const ids=["infoButton","infoButtonBottom","editButton","rotationSelect","situationNameInput","saveSituation","addSituation","deleteSituation","stepNumber","stepTotal","prevStep","playButton","nextStep","stepEditPanel","stepNameWrap","stepNameInput","saveStep","addStep","deleteStep","editPanel","situationSelect","currentStepTitle","court","validationLayer","movementLayer","ballPathLayer","playerLayer","ballObject","tapNotice","status","infoDialog","closeInfo","closeInfoBottom","infoSituation","lineupToggle","lineupChevron","lineupEditor","lineupGrid","liberoToggle","syncBadge","passwordDialog","closePassword","cancelPassword","confirmPassword","passwordInput","passwordStatus"];
const e=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const roleNames={AA:"Außen",MB:"Mitte",Z:"Zuspiel",D:"Diagonal",L:"Libero"};
const rot=(p,n)=>{let r=p;for(let i=0;i<n;i++)r=r===1?6:r-1;return r};
const initialStep=r=>{const positions={};ownRoster.forEach(p=>positions[p.id]={...ownSlots[rot(p.base,r)]});opponentRoster.forEach(p=>positions[p.id]={...opponentSlots[p.base]});return{name:"Grundposition",situation:"serveReceive",positions,ball:{x:450,y:650}}};
const defaultSituationName=i=>i===0?"Grundaufstellung":`Grundaufstellung +${i}`;
const fresh=()=>({rotation:0,step:0,teamConfig:{roles:{...defaultRoles},libero:false},rotations:Array.from({length:6},(_,r)=>({name:defaultSituationName(r),rotationOffset:r,steps:[initialStep(r)]}))});
let state;try{state=JSON.parse(localStorage.getItem(KEY)||"null")||fresh()}catch{state=fresh()}
function migrate(){
  if(!state||!Array.isArray(state.rotations)||!state.rotations.length){state=fresh();return}
  state.teamConfig=state.teamConfig||{roles:{...defaultRoles},libero:false};state.teamConfig.roles={...defaultRoles,...(state.teamConfig.roles||{})};state.teamConfig.libero=Boolean(state.teamConfig.libero);
  state.rotations.forEach((rotation,r)=>{rotation.name=rotation.name||defaultSituationName(r);rotation.rotationOffset=Number.isFinite(Number(rotation.rotationOffset))?Number(rotation.rotationOffset)%6:r%6;if(!Array.isArray(rotation.steps)||!rotation.steps.length)rotation.steps=[initialStep(rotation.rotationOffset)];rotation.steps.forEach(step=>{step.positions=step.positions||{};ownRoster.forEach(p=>{if(!step.positions[p.id])step.positions[p.id]={...ownSlots[rot(p.base,rotation.rotationOffset)]}});opponentRoster.forEach(p=>{if(!step.positions[p.id])step.positions[p.id]={...opponentSlots[p.base]}});if(!step.ball)step.ball={x:450,y:650};if(!step.situation)step.situation="serveReceive";if(!step.name)step.name="Grundposition"})});
  state.rotation=Math.max(0,Math.min(state.rotations.length-1,Number(state.rotation)||0));state.step=Math.max(0,Math.min(state.rotations[state.rotation].steps.length-1,Number(state.step)||0));
}
migrate();
let editing=false,selected=null,dragging=null,playing=false,animations=[],editorPassword=null,lineupOpen=false;
const rd=()=>state.rotations[state.rotation],sd=()=>rd().steps[state.step],rname=n=>state.rotations[n]?.name||defaultSituationName(n),prot=p=>rot(p.base,rd().rotationOffset||0),pat=n=>ownRoster.find(p=>prot(p)===n);
const supabaseConfigured=()=>Boolean(window.APP_CONFIG?.SUPABASE_URL&&window.APP_CONFIG?.SUPABASE_ANON_KEY);
function rpcHeaders(){return{"Content-Type":"application/json",apikey:window.APP_CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${window.APP_CONFIG.SUPABASE_ANON_KEY}`}}
async function rpc(name,body={}){const base=window.APP_CONFIG.SUPABASE_URL.replace(/\/$/,"");const res=await fetch(`${base}/rest/v1/rpc/${name}`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify(body)});if(!res.ok)throw new Error((await res.text())||`HTTP ${res.status}`);const text=await res.text();return text?JSON.parse(text):null}
async function loadRemote(){
  if(!supabaseConfigured()){e.syncBadge.textContent="Speicherung: Browser (Supabase noch nicht konfiguriert)";return}
  e.syncBadge.textContent="Speicherung: Supabase verbunden";
  try{const remote=await rpc("load_trainer_state");if(remote&&Array.isArray(remote.rotations)){state=remote;migrate();localStorage.setItem(KEY,JSON.stringify(state));buildLineupEditor();render();e.status.textContent="Daten aus Supabase geladen."}else e.status.textContent="Supabase verbunden. Noch keine gespeicherte Aufstellung vorhanden."}
  catch(err){e.syncBadge.textContent="Speicherung: Browser (Supabase nicht erreichbar)";e.status.textContent=`Supabase konnte nicht geladen werden: ${err.message}`}
}
async function save(msg){
  localStorage.setItem(KEY,JSON.stringify(state));e.status.textContent=msg;
  if(supabaseConfigured()&&editorPassword!==null){try{await rpc("save_trainer_state",{p_password:editorPassword,p_payload:state});e.syncBadge.textContent="Speicherung: Supabase synchron"}catch(err){e.syncBadge.textContent="Speicherung: Browser; Supabase-Fehler";e.status.textContent=`${msg} Lokal gespeichert. Supabase: ${err.message}`}}
}
function ownRole(p){return state.teamConfig.roles[p.id]||defaultRoles[p.id]||"AA"}
function effectiveRole(p){if(p.team==="opponent")return p.role;const role=ownRole(p);return state.teamConfig.libero&&role==="MB"&&[1,5,6].includes(prot(p))?"L":role}
function svg(name,a={}){const x=document.createElementNS("http://www.w3.org/2000/svg",name);Object.entries(a).forEach(([k,v])=>x.setAttribute(k,v));return x}
function createPlayers(){e.playerLayer.innerHTML="";allPlayers.forEach(p=>{const g=svg("g",{class:`player-object ${p.team}`,"data-id":p.id}),c=svg("circle",{r:29,fill:p.team==="opponent"?"#e32828":"#0b4fc6",stroke:"#fff","stroke-width":3,filter:"url(#shadow)"}),t=svg("text",{"text-anchor":"middle",y:7,fill:"#fff","font-size":19,"font-weight":800,"data-role":"1"}),l=svg("text",{"text-anchor":"middle",y:50,fill:"#fff","font-size":13,"font-weight":700,"data-label":"1"});g.append(c,t,l);e.playerLayer.appendChild(g)})}
function line(layer,a,b,cls){layer.appendChild(svg("line",{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:cls}))}
function validate(){e.validationLayer.innerHTML="";const bad=new Set;if(sd().situation!=="serveReceive")return bad;const p=n=>sd().positions[pat(n).id];[[4,3],[3,2],[5,6],[6,1]].forEach(([l,r])=>{const L=p(l),R=p(r),b=R.x+29,rem=b-(L.x-29),s=rem<=0?"invalid":rem<=18?"warning":"clear";if(s!=="clear"&&(editing||s==="invalid"))e.validationLayer.appendChild(svg("line",{x1:b,y1:455,x2:b,y2:840,class:s==="invalid"?"validation-invalid":"validation-warning"}));if(s==="invalid"){bad.add(pat(l).id);bad.add(pat(r).id)}});[[4,5],[3,6],[2,1]].forEach(([f,bk])=>{const F=p(f),B=p(bk),b=B.y+29,rem=b-(F.y-29),s=rem<=0?"invalid":rem<=18?"warning":"clear";if(s!=="clear"&&(editing||s==="invalid"))e.validationLayer.appendChild(svg("line",{x1:105,y1:b,x2:595,y2:b,class:s==="invalid"?"validation-invalid":"validation-warning"}));if(s==="invalid"){bad.add(pat(f).id);bad.add(pat(bk).id)}});return bad}
function paths(){e.movementLayer.innerHTML="";e.ballPathLayer.innerHTML="";if(state.step===0)return;const a=rd().steps[state.step-1],b=sd();allPlayers.forEach(p=>{const A=a.positions[p.id],B=b.positions[p.id];if(A&&B&&(A.x!==B.x||A.y!==B.y))line(e.movementLayer,A,B,"movement-path")});if(a.ball.x!==b.ball.x||a.ball.y!==b.ball.y)line(e.ballPathLayer,a.ball,b.ball,"ball-path")}
function renderSituationOptions(){
  const current=String(state.rotation);e.rotationSelect.innerHTML="";state.rotations.forEach((situation,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=situation.name||defaultSituationName(i);e.rotationSelect.appendChild(o)});e.rotationSelect.value=current;e.situationNameInput.value=rd().name||defaultSituationName(state.rotation)
}
function render(){
  renderSituationOptions();e.stepNumber.textContent=state.step+1;e.stepTotal.textContent=rd().steps.length;e.stepNameInput.value=sd().name;e.currentStepTitle.textContent=sd().name;e.situationSelect.value=sd().situation;e.liberoToggle.checked=state.teamConfig.libero;document.body.classList.toggle("editing-mode",editing);document.querySelectorAll(".mode-card").forEach(c=>c.classList.toggle("active",c.querySelector("input").checked));paths();const bad=validate();
  allPlayers.forEach(p=>{const g=e.playerLayer.querySelector(`[data-id="${p.id}"]`),pos=sd().positions[p.id],role=effectiveRole(p);g.setAttribute("transform",`translate(${pos.x} ${pos.y})`);g.classList.toggle("editable",editing);g.classList.toggle("selected",selected?.type==="player"&&selected.id===p.id);g.classList.toggle("position-warning",bad.has(p.id)&&p.team==="own");g.querySelector("[data-role]").textContent=role;g.querySelector("circle").setAttribute("fill",p.team==="opponent"?"#e32828":role==="L"?"#111827":"#0b4fc6");g.querySelector("[data-label]").textContent=p.team==="opponent"?`Gegner · P${p.base}`:role==="L"?`Libero · Position ${prot(p)}`:`${roleNames[role]||role} · Position ${prot(p)}`});
  e.ballObject.setAttribute("visibility","visible");e.ballObject.setAttribute("transform",`translate(${sd().ball.x} ${sd().ball.y})`);e.ballObject.classList.toggle("editable",editing);e.ballObject.classList.toggle("selected",selected?.type==="ball");
}
function buildLineupEditor(){
  e.lineupGrid.innerHTML="";ownRoster.forEach((p,i)=>{const label=document.createElement("label");label.className="player-role";label.textContent=`Spieler ${i+1} · Startposition ${p.base}`;const select=document.createElement("select");select.dataset.playerId=p.id;[["AA","Außen (AA)"],["MB","Mitte (MB)"],["Z","Zuspiel (Z)"],["D","Diagonal (D)"]].forEach(([v,t])=>{const o=document.createElement("option");o.value=v;o.textContent=t;select.appendChild(o)});select.value=ownRole(p);select.addEventListener("change",()=>{state.teamConfig.roles[p.id]=select.value;render();save("Aufstellung geändert.")});label.appendChild(select);e.lineupGrid.appendChild(label)});e.liberoToggle.checked=state.teamConfig.libero
}
function stop(){playing=false;animations.forEach(a=>a.cancel());animations=[];e.playButton.textContent="▶"}
function edit(v){stop();editing=v;selected=dragging=null;e.editButton.textContent=v?"✓ Fertig":"✎ Bearbeiten";[e.stepEditPanel,e.editPanel].forEach(x=>x.classList.toggle("hidden",!v));e.tapNotice.classList.add("hidden");if(!v){lineupOpen=false;e.lineupEditor.classList.add("hidden");e.lineupChevron.textContent="▾"}render()}
async function validatePassword(password){if(!supabaseConfigured())return password===TEST_PASSWORD;try{return Boolean(await rpc("validate_editor_password",{p_password:password}))}catch(err){e.passwordStatus.textContent=`Supabase-Prüfung fehlgeschlagen: ${err.message}`;return false}}
async function requestEdit(){if(editing){edit(false);return}e.passwordInput.value="";e.passwordStatus.textContent="";e.passwordDialog.showModal();setTimeout(()=>e.passwordInput.focus(),50)}
async function confirmPassword(){const pwd=e.passwordInput.value;e.confirmPassword.disabled=true;e.passwordStatus.textContent="Prüfe Passwort …";const ok=await validatePassword(pwd);e.confirmPassword.disabled=false;if(!ok){e.passwordStatus.textContent="Passwort ist nicht korrekt.";return}editorPassword=pwd;e.passwordDialog.close();edit(true)}
function point(ev){const p=e.court.createSVGPoint();p.x=ev.clientX;p.y=ev.clientY;return p.matrixTransform(e.court.getScreenCTM().inverse())}
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function playerPoint(p,player){if(sd().situation==="serveReceive"){const yMin=player.team==="own"?479:79,yMax=player.team==="own"?821:421;return{x:clamp(p.x,124,576),y:clamp(p.y,yMin,yMax)}}return{x:clamp(p.x,32,668),y:clamp(p.y,32,868)}}
const cb=p=>({x:clamp(p.x,25,675),y:clamp(p.y,25,875)}),mode=()=>document.querySelector('input[name="moveMode"]:checked').value;
function keepServeReceiveInside(){if(sd().situation!=="serveReceive")return;allPlayers.forEach(player=>{sd().positions[player.id]=playerPoint(sd().positions[player.id],player)})}
e.court.addEventListener("pointerdown",ev=>{if(!editing||playing)return;ev.preventDefault();const pe=ev.target.closest("[data-id]"),be=ev.target.closest("#ballObject");if(mode()==="tap"){if(selected){if(selected.type==="player"&&pe?.dataset.id===selected.id){selected=null;e.tapNotice.classList.add("hidden");render();return}const p=point(ev);if(selected.type==="player"){const player=allPlayers.find(x=>x.id===selected.id);sd().positions[selected.id]=playerPoint(p,player)}else sd().ball=cb(p);selected=null;e.tapNotice.classList.add("hidden");render();return}if(pe){selected={type:"player",id:pe.dataset.id};e.tapNotice.classList.remove("hidden");render();return}if(be){selected={type:"ball"};e.tapNotice.classList.remove("hidden");render();return}return}if(pe){dragging={type:"player",id:pe.dataset.id};e.court.setPointerCapture(ev.pointerId)}else if(be){dragging={type:"ball"};e.court.setPointerCapture(ev.pointerId)}},{passive:false});
e.court.addEventListener("pointermove",ev=>{if(!dragging||!editing||playing)return;ev.preventDefault();const p=point(ev);if(dragging.type==="player"){const player=allPlayers.find(x=>x.id===dragging.id);sd().positions[dragging.id]=playerPoint(p,player)}else sd().ball=cb(p);render()},{passive:false});["pointerup","pointercancel"].forEach(n=>e.court.addEventListener(n,()=>dragging=null));
async function animate(target){target=Math.max(0,Math.min(rd().steps.length-1,target));if(target===state.step)return;stop();const a=sd(),b=rd().steps[target];playing=true;e.playButton.textContent="■";e.movementLayer.innerHTML="";e.ballPathLayer.innerHTML="";allPlayers.forEach(p=>{const A=a.positions[p.id],B=b.positions[p.id];if(A&&B&&(A.x!==B.x||A.y!==B.y))line(e.movementLayer,A,B,"movement-path")});if(a.ball.x!==b.ball.x||a.ball.y!==b.ball.y)line(e.ballPathLayer,a.ball,b.ball,"ball-path");const pa=allPlayers.map(p=>e.playerLayer.querySelector(`[data-id="${p.id}"]`).animate([{transform:`translate(${a.positions[p.id].x}px,${a.positions[p.id].y}px)`},{transform:`translate(${b.positions[p.id].x}px,${b.positions[p.id].y}px)`}],{duration:1450,easing:"ease-in-out",fill:"forwards"}));const ba=e.ballObject.animate([{transform:`translate(${a.ball.x}px,${a.ball.y}px) rotate(0deg)`},{transform:`translate(${b.ball.x}px,${b.ball.y}px) rotate(360deg)`}],{duration:1450,easing:"ease-in-out",fill:"forwards"});animations=[...pa,ba];await Promise.all(animations.map(x=>x.finished.catch(()=>{})));if(!playing)return;state.step=target;playing=false;animations=[];e.playButton.textContent="▶";render()}
e.prevStep.addEventListener("click",()=>animate(state.step-1));e.nextStep.addEventListener("click",()=>animate(state.step+1));e.playButton.addEventListener("click",()=>{if(playing){stop();render();return}if(rd().steps.length<2){e.status.textContent="Lege zuerst einen zweiten Schritt an.";return}animate(state.step>=rd().steps.length-1?0:state.step+1)});
e.editButton.addEventListener("click",requestEdit);e.rotationSelect.addEventListener("change",x=>{state.rotation=Number(x.target.value);state.step=0;buildLineupEditor();render()});e.saveSituation.addEventListener("click",()=>{rd().name=e.situationNameInput.value.trim()||defaultSituationName(state.rotation);save("Spielsituation gespeichert.");render()});e.addSituation.addEventListener("click",()=>{const copy=structuredClone(rd());copy.name=`Neue Spielsituation ${state.rotations.length+1}`;state.rotations.splice(state.rotation+1,0,copy);state.rotation++;state.step=0;save("Neue Spielsituation angelegt.");render()});e.deleteSituation.addEventListener("click",()=>{if(state.rotations.length===1){e.status.textContent="Die einzige Spielsituation kann nicht gelöscht werden.";return}state.rotations.splice(state.rotation,1);state.rotation=Math.max(0,state.rotation-1);state.step=0;save("Spielsituation gelöscht.");render()});e.situationSelect.addEventListener("change",x=>{sd().situation=x.target.value;keepServeReceiveInside();render()});
e.saveStep.addEventListener("click",()=>{sd().name=e.stepNameInput.value.trim()||`Schritt ${state.step+1}`;keepServeReceiveInside();save("Schritt gespeichert.");render()});
e.addStep.addEventListener("click",()=>{sd().name=e.stepNameInput.value.trim()||`Schritt ${state.step+1}`;keepServeReceiveInside();const s=sd();rd().steps.splice(state.step+1,0,{name:`Schritt ${state.step+2}`,situation:s.situation,positions:structuredClone(s.positions),ball:structuredClone(s.ball)});state.step++;save("Neuer Schritt angelegt.");render()});
e.deleteStep.addEventListener("click",()=>{if(rd().steps.length===1){e.status.textContent="Der einzige Schritt kann nicht gelöscht werden.";return}rd().steps.splice(state.step,1);state.step=Math.max(0,state.step-1);save("Schritt gelöscht.");render()});
document.querySelectorAll('input[name="moveMode"]').forEach(i=>i.addEventListener("change",()=>{selected=null;e.tapNotice.classList.add("hidden");render()}));
e.lineupToggle.addEventListener("click",()=>{lineupOpen=!lineupOpen;e.lineupEditor.classList.toggle("hidden",!lineupOpen);e.lineupChevron.textContent=lineupOpen?"▴":"▾"});e.liberoToggle.addEventListener("change",()=>{state.teamConfig.libero=e.liberoToggle.checked;render();save(state.teamConfig.libero?"Libero aktiviert.":"Libero deaktiviert.")});
e.confirmPassword.addEventListener("click",confirmPassword);e.passwordInput.addEventListener("keydown",ev=>{if(ev.key==="Enter")confirmPassword()});[e.closePassword,e.cancelPassword].forEach(x=>x.addEventListener("click",()=>e.passwordDialog.close()));
function info(){e.infoSituation.textContent=`Aktuell: ${rname(state.rotation)} · Schritt ${state.step+1} · ${sd().name}`;e.infoDialog.showModal()}e.infoButton.addEventListener("click",info);e.infoButtonBottom.addEventListener("click",info);e.closeInfo.addEventListener("click",()=>e.infoDialog.close());e.closeInfoBottom.addEventListener("click",()=>e.infoDialog.close());e.infoDialog.addEventListener("click",x=>{if(x.target===e.infoDialog)e.infoDialog.close()});
createPlayers();buildLineupEditor();edit(false);loadRemote();
})();
