window.APP_CONFIG = {
  SUPABASE_URL: "https://mvwwwkigsoaodllbtifj.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_gwDoKpExqBfM4voiXncaaA_w61xcbO4"
};
(() => {
  const version = "3.14.14";
  const asset=(tag,attrs)=>{if(document.querySelector(`${tag}[data-vb-release="${attrs['data-vb-release']}"]`))return;const el=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));(tag==='link'?document.head:document.body).appendChild(el)};
  const showLoadedVersion=()=>{const club=document.getElementById('brandClubName');if(!club)return;let line=document.getElementById('brandVersion');if(!line){line=document.createElement('div');line.id='brandVersion';club.insertAdjacentElement('afterend',line)}line.textContent=version;line.setAttribute('aria-label',`Version ${version}`);line.style.cssText='font-size:.68rem;line-height:1.05;opacity:.68;margin-top:-1px'};
  const workspaceHead=()=>document.getElementById('editorWorkspaceHead')||document.querySelector('.editor-workspace-head');
  const isEditing=()=>{const p=document.getElementById('editPanel');return !!p&&!p.classList.contains('hidden')};
  const closeExerciseUi=()=>{document.body.classList.remove('exercise-library-open');document.getElementById('exerciseLibraryWorkspace')?.classList.add('hidden');document.querySelectorAll('.exercise-editor-overlay').forEach(el=>el.remove())};
  const resetAddonUi=()=>{if(!isEditing()){closeExerciseUi();workspaceHead()?.querySelectorAll('.music-density-buttons').forEach(x=>x.remove());return}if(!document.body.classList.contains('exercise-library-open'))document.getElementById('exerciseLibraryWorkspace')?.classList.add('hidden')};
  const installEditorModeReconcile=()=>{const b=document.getElementById('editButton');if(!b||b.dataset.vbModeReconcile)return;b.dataset.vbModeReconcile='1';b.addEventListener('click',()=>requestAnimationFrame(resetAddonUi))};
  const installCompactBackButton=()=>{const b=document.getElementById('editorWorkspaceBack');if(!b)return;b.textContent='←';b.setAttribute('aria-label','Zurück zu Bereiche');b.title='Zurück zu Bereiche'};
  const installMusicDensityButtons=()=>{const select=document.getElementById('musicFontSize'),head=workspaceHead();if(!select||!head||!document.body.classList.contains('editor-workspace-playlists'))return;let wrap=head.querySelector('.music-density-buttons');if(!wrap){wrap=document.createElement('div');wrap.className='music-density-buttons';[['small','S'],['medium','M'],['large','L']].forEach(([value,label])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.size=value;b.title=label==='S'?'Klein':label==='M'?'Mittel':'Groß';b.onclick=()=>{select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));sync()};wrap.appendChild(b)});head.appendChild(wrap)}const sync=()=>wrap.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.size===select.value));if(!select.dataset.vbDensitySync){select.dataset.vbDensitySync='1';select.addEventListener('change',sync)}sync()};
  const compactMusicSections=()=>{const dialog=document.getElementById('musicLibraryDialog');if(!dialog||dialog.dataset.vbCompactSections==='3')return;const upload=[...dialog.querySelectorAll('details')].find(d=>/Eigene Titel hochladen/i.test(d.querySelector('summary')?.textContent||''));const playlistSection=[...dialog.querySelectorAll('section.music-library-section')].find(s=>/Playlists/i.test(s.querySelector('.music-playlist-head')?.textContent||''));if(!upload||!playlistSection)return;let playlist=dialog.querySelector('details.music-playlist-details');if(!playlist){playlist=document.createElement('details');playlist.className='music-library-section music-playlist-details';const summary=document.createElement('summary');summary.textContent='Playlists';playlist.appendChild(summary);playlistSection.parentNode.insertBefore(playlist,playlistSection);playlist.appendChild(playlistSection)}upload.parentNode.insertBefore(playlist,upload);playlist.open=false;upload.open=false;if(!playlist.dataset.vbAccordion){playlist.dataset.vbAccordion='1';playlist.addEventListener('toggle',()=>{if(playlist.open)upload.open=false});upload.addEventListener('toggle',()=>{if(upload.open)playlist.open=false})}dialog.dataset.vbCompactSections='3'};
  let lastMode='';
  const syncWorkspaceAddons=()=>{const mode=[...document.body.classList].find(x=>x.startsWith('editor-workspace-'))||'';if(mode===lastMode)return;lastMode=mode;installCompactBackButton();if(mode==='editor-workspace-playlists'){installMusicDensityButtons();compactMusicSections()}else workspaceHead()?.querySelectorAll('.music-density-buttons').forEach(x=>x.remove());if(mode!=='editor-workspace-hub'&&mode!=='')document.getElementById('editorHub')?.classList.add('hidden')};
  const load=()=>{showLoadedVersion();installEditorModeReconcile();asset('link',{rel:'stylesheet',href:`ui-3.14.4.css?v=${version}`,'data-vb-release':'ui-css'});asset('link',{rel:'stylesheet',href:`exercise-library.css?v=${version}`,'data-vb-release':'exercise-css'});asset('link',{rel:'stylesheet',href:`ui-3.14.12.css?v=${version}`,'data-vb-release':'ui-31412'});asset('link',{rel:'stylesheet',href:`ui-3.14.13.css?v=${version}`,'data-vb-release':'ui-31413'});asset('link',{rel:'stylesheet',href:`ui-3.14.14.css?v=${version}`,'data-vb-release':'ui-31414'});asset('script',{src:`feature-admin.js?v=${version}`,'data-vb-release':'feature-admin'});asset('script',{src:`exercise-library.js?v=${version}`,'data-vb-release':'exercise-js'});installCompactBackButton();syncWorkspaceAddons();const observer=new MutationObserver(syncWorkspaceAddons);observer.observe(document.body,{attributes:true,attributeFilter:['class']})};
  if(document.readyState==='complete')load();else window.addEventListener('load',load,{once:true});
})();