window.APP_CONFIG = {
  SUPABASE_URL: "https://mvwwwkigsoaodllbtifj.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_gwDoKpExqBfM4voiXncaaA_w61xcbO4"
};
(() => {
  const version = "3.14.12";
  const asset=(tag,attrs)=>{if(document.querySelector(`${tag}[data-vb-release="${attrs['data-vb-release']}"]`))return;const el=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));(tag==='link'?document.head:document.body).appendChild(el)};
  const showLoadedVersion=()=>{const club=document.getElementById('brandClubName');if(!club)return;let line=document.getElementById('brandVersion');if(!line){line=document.createElement('div');line.id='brandVersion';club.insertAdjacentElement('afterend',line)}line.textContent=version;line.setAttribute('aria-label',`Version ${version}`);line.style.cssText='font-size:.68rem;line-height:1.05;opacity:.68;margin-top:-1px'};
  const closeExerciseUi=()=>{document.body.classList.remove('exercise-library-open');document.getElementById('exerciseLibraryWorkspace')?.classList.add('hidden');document.querySelectorAll('.exercise-editor-overlay').forEach(el=>el.remove())};
  const reconcileEditorUi=()=>{const editPanel=document.getElementById('editPanel'),hub=document.getElementById('editorHub'),editing=!!editPanel&&!editPanel.classList.contains('hidden');if(!editing){closeExerciseUi();document.body.classList.remove('editor-workspace-hub');hub?.classList.add('hidden');return}if(!document.body.classList.contains('exercise-library-open')){document.body.classList.add('editor-workspace-hub');hub?.classList.remove('hidden')}};
  const installEditorModeReconcile=()=>{const b=document.getElementById('editButton');if(!b||b.dataset.vbModeReconcile)return;b.dataset.vbModeReconcile='1';b.addEventListener('click',()=>setTimeout(reconcileEditorUi,0))};
  const installMusicDensityButtons=()=>{const select=document.getElementById('musicFontSize'),head=document.getElementById('editorWorkspaceHead');if(!select||!head||head.querySelector('.music-density-buttons'))return;const wrap=document.createElement('div');wrap.className='music-density-buttons';[['small','S'],['medium','M'],['large','L']].forEach(([value,label])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.size=value;b.onclick=()=>{select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));sync()};wrap.appendChild(b)});head.appendChild(wrap);const sync=()=>wrap.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.size===select.value));select.addEventListener('change',sync);sync()};
  const compactMusicSections=()=>{const dialog=document.getElementById('musicLibraryDialog');if(!dialog||dialog.dataset.vbCompactSections)return;dialog.dataset.vbCompactSections='1';const upload=[...dialog.querySelectorAll('details')].find(d=>/Eigene Titel hochladen/i.test(d.querySelector('summary')?.textContent||''));const playlist=[...dialog.querySelectorAll('details')].find(d=>/Playlist/i.test(d.querySelector('summary')?.textContent||''));if(playlist&&upload){playlist.open=false;upload.open=false;upload.parentNode.insertBefore(playlist,upload);const closeOther=e=>{if(e.target.open){(e.target===playlist?upload:playlist).open=false}};playlist.addEventListener('toggle',closeOther);upload.addEventListener('toggle',closeOther)}};
  const load=()=>{showLoadedVersion();installEditorModeReconcile();asset('link',{rel:'stylesheet',href:`ui-3.14.4.css?v=${version}`,'data-vb-release':'ui-css'});asset('link',{rel:'stylesheet',href:`exercise-library.css?v=${version}`,'data-vb-release':'exercise-css'});asset('link',{rel:'stylesheet',href:`ui-3.14.12.css?v=${version}`,'data-vb-release':'ui-31412'});asset('script',{src:`feature-admin.js?v=${version}`,'data-vb-release':'feature-admin'});asset('script',{src:`exercise-library.js?v=${version}`,'data-vb-release':'exercise-js'});setTimeout(()=>{installMusicDensityButtons();compactMusicSections()},0)};
  if(document.readyState==='complete')load();else window.addEventListener('load',load,{once:true});
})();