(()=>{'use strict';
const API=()=>window.VBTrainingApi,FEATURE='exercise_library',ACCESS_KEY='volleyball-trainer-access-v3';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function isPlatformAdmin(){try{return !!JSON.parse(localStorage.getItem(ACCESS_KEY)||'null')?.platform_admin}catch{return false}}
async function rpc(name,body){return API().request(`/rest/v1/rpc/${name}`,{method:'POST',body})}
function section(data){const f=data?.feature;if(!f)return '<p class="admin-error">Feature-Konfiguration konnte nicht geladen werden.</p>';return `<section class="admin-section feature-admin-panel" id="featureAdminPanel"><h3>Feature-Freigaben</h3><div class="feature-row"><strong>${esc(f.label)} ${f.beta?'· Beta':''}</strong><label><input id="featureGlobal" type="checkbox" ${f.global_enabled?'checked':''}> global aktiv</label></div><p class="hint">Superadmins haben immer Zugriff. Für Vereine können zusätzlich Vereinsadmins, Bearbeiter oder einzelne Benutzer freigeschaltet werden.</p>${(data.clubs||[]).map(c=>`<article class="feature-club" data-club="${esc(c.club_id)}"><strong>${esc(c.club_name)}</strong><div class="feature-row"><label><input data-k="grant" type="checkbox" ${c.platform_granted?'checked':''}> Verein freigeben</label><label><input data-k="enabled" type="checkbox" ${c.club_enabled?'checked':''}> im Verein aktiv</label><label><input data-k="admins" type="checkbox" ${c.allow_club_admins?'checked':''}> Vereinsadmins</label><label><input data-k="editors" type="checkbox" ${c.allow_editors?'checked':''}> Bearbeiter</label></div><div class="feature-users">${(c.users||[]).map(u=>`<label><input data-user="${esc(u.user_id)}" type="checkbox" ${u.enabled?'checked':''}> ${esc(u.display_name||u.user_id)}</label>`).join('')||'<span class="hint">Keine Bearbeiter/Vereinsadmins vorhanden.</span>'}</div><button class="primary feature-save" type="button">Freigabe speichern</button><span class="feature-status"></span></article>`).join('')}</section>`}
async function install(){if(!isPlatformAdmin()||!API())return;const content=document.getElementById('platformAdminContent');if(!content)return;const render=async()=>{try{const data=await rpc('get_feature_admin_overview',{p_feature_key:FEATURE});document.getElementById('featureAdminPanel')?.remove();content.insertAdjacentHTML('beforeend',section(data));wire(content)}catch(e){console.warn('Feature admin:',e)}};const obs=new MutationObserver(()=>{if(content.childElementCount&&!document.getElementById('featureAdminPanel'))render()});obs.observe(content,{childList:true});if(content.childElementCount)render()}
function wire(root){root.querySelectorAll('.feature-save').forEach(btn=>btn.onclick=async()=>{const card=btn.closest('.feature-club'),status=card.querySelector('.feature-status'),users=[...card.querySelectorAll('[data-user]:checked')].map(x=>x.dataset.user);btn.disabled=true;status.textContent='Wird gespeichert …';try{await rpc('set_feature_admin_config',{p_feature_key:FEATURE,p_global_enabled:document.getElementById('featureGlobal').checked,p_club_id:card.dataset.club,p_platform_granted:card.querySelector('[data-k="grant"]').checked,p_club_enabled:card.querySelector('[data-k="enabled"]').checked,p_allow_club_admins:card.querySelector('[data-k="admins"]').checked,p_allow_editors:card.querySelector('[data-k="editors"]').checked,p_enabled_users:users});status.textContent='Gespeichert.';document.dispatchEvent(new CustomEvent('vb-feature-access-changed'))}catch(e){status.textContent=`Fehler: ${e.message}`}finally{btn.disabled=false}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();