(() => {
"use strict";

const VERSION="3.7.0";
const BUILTIN=[
  {id:"danza",title:"Danza",artist:"Ronald Kah",genre:"Electronic",bpm:136,duration:238,parts:7,local:true},
  {id:"danza-ii",title:"Danza II",artist:"Ronald Kah",genre:"Electronic",bpm:136,duration:258,parts:8,local:true},
  {id:"danza-iii",title:"Danza III",artist:"Ronald Kah",genre:"Electronic",bpm:129,duration:290,parts:9,local:true},
  {id:"danza-iv",title:"Danza IV",artist:"Ronald Kah",genre:"Electronic",bpm:129,duration:235,parts:7,local:true},
  {id:"night-dance",title:"Night Dance",artist:"Ronald Kah",genre:"Electronic",bpm:136,duration:115,parts:4,local:true}
];
const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
const formatTime=value=>`${Math.floor(Number(value||0)/60)}:${String(Math.round(Number(value||0))%60).padStart(2,"0")}`;
const safeName=value=>String(value||"music").normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/^-+|-+$/g,"").slice(-100)||"music.mp3";
const trackParts=track=>Array.from({length:track.parts||0},(_,index)=>`assets/music/ronald-kah/chunks/${track.id}.part-${String(index+1).padStart(2,"0")}.mp3`);

class MusicLibrary {
  constructor(){
    this.userId="";this.teamId="";this.clubId="";this.remote=[];this.playlists=[];this.currentPlaylistId="";this.preview=new Audio();this.preview.preload="metadata";this.previewUrl="";
    this.dialog=document.getElementById("musicLibraryDialog");
    const ids=["musicLibraryOpen","musicLibraryClose","musicLibraryRefresh","musicLibrarySearch","musicLibraryGenre","musicLibraryBpm","musicTrackList","musicUploadForm","musicUploadFile","musicUploadTitle","musicUploadArtist","musicUploadGenre","musicUploadBpm","musicUploadLicense","musicUploadSubmit","musicPlaylistSelect","musicPlaylistName","musicPlaylistVisibility","musicPlaylistTracks","musicPlaylistNew","musicPlaylistSave","musicPlaylistCopy","musicPlaylistDelete","musicLibraryStatus"];
    this.e=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));this.bind();
  }
  api(){if(!window.VBTrainingApi)throw new Error("Musikverwaltung ist noch nicht bereit.");return window.VBTrainingApi}
  setContext({userId="",teamId="",clubId=""}={}){const changed=this.userId!==userId||this.teamId!==teamId||this.clubId!==clubId;this.userId=userId;this.teamId=teamId;this.clubId=clubId;if(!changed)return;if(!clubId){this.stopPreview();this.remote=[];this.playlists=[];this.currentPlaylistId="";this.render();return}this.load().catch(error=>this.status(error.message,true))}
  tracks(){return [...BUILTIN,...this.remote]}
  trackByKey(key){return this.tracks().find(track=>track.id===key)}
  resolveSelection(value){if(value==="all")return BUILTIN;const playlistId=String(value||"").replace(/^playlist:/,"");const playlist=this.playlists.find(item=>item.id===playlistId);if(playlist)return [...playlist.items].sort((a,b)=>a.sort_order-b.sort_order).map(item=>item.local_track_key?this.trackByKey(item.local_track_key):this.trackByKey(`remote:${item.track_id}`)).filter(Boolean);const track=this.trackByKey(String(value||"danza").replace(/^track:/,""));return track?[track]:[BUILTIN[0]]}
  selectionOptions(selected=""){
    const option=(value,label)=>`<option value="${esc(value)}" ${value===selected?"selected":""}>${esc(label)}</option>`;
    const mine=this.playlists.filter(p=>p.owner_id===this.userId),shared=this.playlists.filter(p=>p.owner_id!==this.userId);
    return `<optgroup label="Mitgelieferte Musik">${option("all","Alle fünf Titel · 129–136 BPM")}${BUILTIN.map(t=>option(t.id,`${t.title} · ${t.bpm} BPM · ${formatTime(t.duration)}`)).join("")}</optgroup>${this.remote.length?`<optgroup label="Vereinsbibliothek">${this.remote.map(t=>option(t.id,`${t.title} · ${t.bpm} BPM · ${formatTime(t.duration)}`)).join("")}</optgroup>`:""}${mine.length?`<optgroup label="Meine Playlists">${mine.map(p=>option(`playlist:${p.id}`,`${p.name} · ${p.items.length} Titel`)).join("")}</optgroup>`:""}${shared.length?`<optgroup label="Freigegebene Playlists">${shared.map(p=>option(`playlist:${p.id}`,`${p.name} · ${p.items.length} Titel`)).join("")}</optgroup>`:""}`;
  }
  async load(){if(!this.clubId)return;this.status("Musikbibliothek wird geladen …");const tracks=await this.api().request(`/rest/v1/vt_music_tracks?select=id,owner_id,title,artist,genre,bpm_original,duration_seconds,storage_path,license_note&club_id=eq.${encodeURIComponent(this.clubId)}&active=eq.true&order=title.asc`);this.remote=await Promise.all((tracks||[]).map(async row=>({id:`remote:${row.id}`,remoteId:row.id,title:row.title,artist:row.artist,genre:row.genre,bpm:row.bpm_original,duration:row.duration_seconds,storagePath:row.storage_path,licenseNote:row.license_note,ownerId:row.owner_id,url:await this.api().signMusic(row.storage_path)})));const playlists=await this.api().request(`/rest/v1/vt_music_playlists?select=id,owner_id,name,visibility,team_id,vt_music_playlist_items(id,sort_order,track_id,local_track_key)&club_id=eq.${encodeURIComponent(this.clubId)}&order=name.asc`);this.playlists=(playlists||[]).map(p=>({...p,items:p.vt_music_playlist_items||[]}));this.render();this.status(`${this.tracks().length} Titel und ${this.playlists.length} Playlists verfügbar.`);document.dispatchEvent(new CustomEvent("vb-music-library-updated"))}
  bind(){
    this.e.musicLibraryOpen?.addEventListener("click",()=>this.open());this.e.musicLibraryClose?.addEventListener("click",()=>this.close());this.e.musicLibraryRefresh?.addEventListener("click",()=>this.load().catch(e=>this.status(e.message,true)));
    [this.e.musicLibrarySearch,this.e.musicLibraryGenre,this.e.musicLibraryBpm].forEach(control=>control?.addEventListener("input",()=>this.renderTracks()));
    this.e.musicTrackList?.addEventListener("click",event=>this.trackAction(event));this.e.musicUploadForm?.addEventListener("submit",event=>this.upload(event));
    this.e.musicPlaylistSelect?.addEventListener("change",()=>this.selectPlaylist(this.e.musicPlaylistSelect.value));this.e.musicPlaylistNew?.addEventListener("click",()=>this.newPlaylist());this.e.musicPlaylistSave?.addEventListener("click",()=>this.savePlaylist());this.e.musicPlaylistCopy?.addEventListener("click",()=>this.copyPlaylist());this.e.musicPlaylistDelete?.addEventListener("click",()=>this.deletePlaylist());
    this.dialog?.addEventListener("click",event=>{if(event.target===this.dialog)this.close()});this.dialog?.addEventListener("cancel",event=>{event.preventDefault();this.close()});
  }
  open(){this.render();this.dialog?.showModal()}
  close(){this.stopPreview();this.dialog?.close()}
  render(){this.renderFilters();this.renderTracks();this.renderPlaylistSelect();this.selectPlaylist(this.currentPlaylistId||"new")}
  renderFilters(){const genres=[...new Set(this.tracks().map(t=>t.genre).filter(Boolean))].sort();const selected=this.e.musicLibraryGenre?.value||"";if(this.e.musicLibraryGenre)this.e.musicLibraryGenre.innerHTML=`<option value="">Alle Stile</option>${genres.map(g=>`<option ${g===selected?"selected":""}>${esc(g)}</option>`).join("")}`}
  filteredTracks(){const q=(this.e.musicLibrarySearch?.value||"").trim().toLowerCase(),genre=this.e.musicLibraryGenre?.value||"",range=this.e.musicLibraryBpm?.value||"";return this.tracks().filter(t=>(!q||`${t.title} ${t.artist}`.toLowerCase().includes(q))&&(!genre||t.genre===genre)&&(!range||(range==="lt100"?t.bpm<100:range==="100-119"?t.bpm<120&&t.bpm>=100:range==="120-129"?t.bpm<130&&t.bpm>=120:range==="130-139"?t.bpm<140&&t.bpm>=130:t.bpm>=140)))}
  renderTracks(){if(!this.e.musicTrackList)return;const rows=this.filteredTracks();this.e.musicTrackList.innerHTML=rows.map(t=>`<article class="music-track-row" data-track="${esc(t.id)}"><button class="music-preview" data-action="preview" type="button" aria-label="${esc(t.title)} vorhören">▶</button><div><strong>${esc(t.title)}</strong><span>${esc(t.artist||"Unbekannt")} · ${esc(t.genre)} · <b>${t.bpm} BPM</b> · ${formatTime(t.duration)}</span></div>${t.ownerId===this.userId?'<button class="danger music-track-delete" data-action="delete" type="button" title="Titel löschen">🗑</button>':''}</article>`).join("")||'<p class="hint">Keine Titel für diesen Filter.</p>';this.renderPlaylistTracks()}
  async playableUrl(track){if(track.url)return track.url;if(this.previewUrl){URL.revokeObjectURL(this.previewUrl);this.previewUrl=""}const responses=await Promise.all(trackParts(track).map(path=>fetch(path)));if(responses.some(r=>!r.ok))throw new Error("Titel konnte nicht geladen werden.");const buffers=await Promise.all(responses.map(r=>r.arrayBuffer()));this.previewUrl=URL.createObjectURL(new Blob(buffers,{type:"audio/mpeg"}));return this.previewUrl}
  async previewSelection(value){const track=this.resolveSelection(value)[0];if(!track)throw new Error("Die Auswahl enthält keinen abspielbaren Titel.");if(this.preview.dataset.track===track.id&&!this.preview.paused){this.stopPreview();this.status("Vorschau beendet.");return}this.stopPreview();this.preview.src=await this.playableUrl(track);this.preview.dataset.track=track.id;await this.preview.play();this.status(`Vorschau: ${track.title} · ${track.bpm} BPM`)}
  async trackAction(event){const button=event.target.closest("button[data-action]"),row=button?.closest("[data-track]");if(!button||!row)return;const track=this.trackByKey(row.dataset.track);if(button.dataset.action==="preview"){if(this.preview.dataset.track===track.id&&!this.preview.paused){this.stopPreview();return}try{this.stopPreview();this.preview.src=await this.playableUrl(track);this.preview.dataset.track=track.id;await this.preview.play();button.textContent="Ⅱ";this.status(`Vorschau: ${track.title} · ${track.bpm} BPM`)}catch(error){this.status(error.message,true)}}else if(button.dataset.action==="delete"&&track.remoteId){if(!confirm(`„${track.title}“ wirklich aus der Vereinsbibliothek löschen?`))return;try{await this.api().deleteMusic(track.storagePath);await this.api().request(`/rest/v1/vt_music_tracks?id=eq.${track.remoteId}`,{method:"DELETE"});await this.load()}catch(error){this.status(error.message,true)}}}
  stopPreview(){this.preview.pause();this.preview.removeAttribute("src");delete this.preview.dataset.track;this.preview.load();this.e.musicTrackList?.querySelectorAll(".music-preview").forEach(b=>b.textContent="▶")}
  async upload(event){event.preventDefault();const file=this.e.musicUploadFile.files?.[0];if(!file) return this.status("Bitte zuerst eine Audiodatei auswählen.",true);if(file.size>31457280)return this.status("Die Datei darf höchstens 30 MB groß sein.",true);const title=this.e.musicUploadTitle.value.trim()||file.name.replace(/\.[^.]+$/,"");const bpm=Number(this.e.musicUploadBpm.value),license=this.e.musicUploadLicense.value.trim();if(bpm<50||bpm>220||!license)return this.status("Bitte BPM und Nutzungsrecht vollständig angeben.",true);this.e.musicUploadSubmit.disabled=true;let path="";try{const duration=await this.audioDuration(file);path=`${this.clubId}/${this.userId}/${crypto.randomUUID()}-${safeName(file.name)}`;await this.api().uploadMusic(path,file);await this.api().request("/rest/v1/vt_music_tracks",{method:"POST",headers:{Prefer:"return=representation"},body:{club_id:this.clubId,owner_id:this.userId,title,artist:this.e.musicUploadArtist.value.trim(),genre:this.e.musicUploadGenre.value.trim()||"Sonstiges",bpm_original:bpm,duration_seconds:Math.max(1,Math.round(duration)),storage_path:path,mime_type:file.type||"audio/mpeg",file_size:file.size,license_note:license}});this.e.musicUploadForm.reset();await this.load();this.status(`„${title}“ wurde hochgeladen.`)}catch(error){if(path)await this.api().deleteMusic(path).catch(()=>{});this.status(error.message,true)}finally{this.e.musicUploadSubmit.disabled=false}}
  audioDuration(file){return new Promise((resolve,reject)=>{const audio=new Audio(),url=URL.createObjectURL(file);audio.preload="metadata";audio.onloadedmetadata=()=>{URL.revokeObjectURL(url);resolve(audio.duration)};audio.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Dauer der Audiodatei konnte nicht gelesen werden."))};audio.src=url})}
  renderPlaylistSelect(){if(!this.e.musicPlaylistSelect)return;const option=p=>`<option value="${p.id}">${esc(p.name)} · ${p.owner_id===this.userId?"Meine":p.visibility==="team"?"Mannschaft":"Verein"}</option>`;this.e.musicPlaylistSelect.innerHTML=`<option value="new">＋ Neue Playlist</option>${this.playlists.map(option).join("")}`;this.e.musicPlaylistSelect.value=this.currentPlaylistId||"new"}
  selectPlaylist(id){const playlist=this.playlists.find(p=>p.id===id);this.currentPlaylistId=playlist?.id||"";const editable=!playlist||playlist.owner_id===this.userId;this.e.musicPlaylistName.value=playlist?.name||"";this.e.musicPlaylistVisibility.value=playlist?.visibility||"private";this.e.musicPlaylistName.disabled=!editable;this.e.musicPlaylistVisibility.disabled=!editable;this.e.musicPlaylistSave.classList.toggle("hidden",!editable);this.e.musicPlaylistDelete.classList.toggle("hidden",!playlist||!editable);this.e.musicPlaylistCopy.classList.toggle("hidden",!playlist||editable);this.renderPlaylistTracks(playlist);if(this.e.musicPlaylistSelect)this.e.musicPlaylistSelect.value=playlist?.id||"new"}
  renderPlaylistTracks(playlist=this.playlists.find(p=>p.id===this.currentPlaylistId)){if(!this.e.musicPlaylistTracks)return;const selected=new Set((playlist?.items||[]).map(item=>item.local_track_key||`remote:${item.track_id}`)),editable=!playlist||playlist.owner_id===this.userId;this.e.musicPlaylistTracks.innerHTML=this.tracks().map(t=>`<label><input type="checkbox" value="${esc(t.id)}" ${selected.has(t.id)?"checked":""} ${editable?"":"disabled"}><span>${esc(t.title)} · <b>${t.bpm} BPM</b></span></label>`).join("")}
  newPlaylist(){this.currentPlaylistId="";this.renderPlaylistSelect();this.selectPlaylist("new");this.e.musicPlaylistName.focus()}
  async savePlaylist(){const name=this.e.musicPlaylistName.value.trim(),visibility=this.e.musicPlaylistVisibility.value,keys=[...this.e.musicPlaylistTracks.querySelectorAll("input:checked")].map(i=>i.value);if(!name||!keys.length)return this.status("Playlist-Name und mindestens einen Titel auswählen.",true);if(visibility==="team"&&!this.teamId)return this.status("Für eine Mannschafts-Playlist muss eine Mannschaft ausgewählt sein.",true);this.e.musicPlaylistSave.disabled=true;try{let id=this.currentPlaylistId;const teamId=visibility==="club"?null:this.teamId;if(id){await this.api().request(`/rest/v1/vt_music_playlists?id=eq.${id}`,{method:"PATCH",body:{name,visibility,team_id:teamId,updated_at:new Date().toISOString()}});await this.api().request(`/rest/v1/vt_music_playlist_items?playlist_id=eq.${id}`,{method:"DELETE"})}else{const rows=await this.api().request("/rest/v1/vt_music_playlists",{method:"POST",headers:{Prefer:"return=representation"},body:{club_id:this.clubId,team_id:teamId,owner_id:this.userId,name,visibility}});id=rows?.[0]?.id}if(!id)throw new Error("Playlist konnte nicht angelegt werden.");const items=keys.map((key,index)=>({playlist_id:id,sort_order:index,...(key.startsWith("remote:")?{track_id:key.slice(7)}:{local_track_key:key})}));await this.api().request("/rest/v1/vt_music_playlist_items",{method:"POST",body:items});this.currentPlaylistId=id;await this.load();this.status(`Playlist „${name}“ gespeichert.`)}catch(error){this.status(error.message,true)}finally{this.e.musicPlaylistSave.disabled=false}}
  copyPlaylist(){const source=this.playlists.find(p=>p.id===this.currentPlaylistId);if(!source)return;this.currentPlaylistId="";this.e.musicPlaylistName.value=`${source.name} – Kopie`;this.e.musicPlaylistVisibility.value="private";this.e.musicPlaylistName.disabled=false;this.e.musicPlaylistVisibility.disabled=false;this.e.musicPlaylistSave.classList.remove("hidden");this.e.musicPlaylistCopy.classList.add("hidden");this.e.musicPlaylistDelete.classList.add("hidden");this.renderPlaylistTracks({...source,owner_id:this.userId});this.e.musicPlaylistSelect.value="new"}
  async deletePlaylist(){const playlist=this.playlists.find(p=>p.id===this.currentPlaylistId);if(!playlist||playlist.owner_id!==this.userId||!confirm(`Playlist „${playlist.name}“ löschen?`))return;try{await this.api().request(`/rest/v1/vt_music_playlists?id=eq.${playlist.id}`,{method:"DELETE"});this.currentPlaylistId="";await this.load()}catch(error){this.status(error.message,true)}}
  status(message,error=false){if(this.e.musicLibraryStatus){this.e.musicLibraryStatus.textContent=message||"";this.e.musicLibraryStatus.classList.toggle("error",Boolean(error))}}
}

window.VBMusicLibrary=new MusicLibrary();
window.VBMusicLibraryInternals={VERSION,BUILTIN,formatTime};
})();
