(()=>{'use strict';
const API=()=>window.VBTrainingApi,ACCESS_KEY='volleyball-trainer-access-v3';
const labels={decision:'Entscheidung',release:'Release',roadmap:'Roadmap',known_issue:'Bekannter Punkt',active:'Aktiv',planned:'Geplant',done:'Erledigt',accepted:'Akzeptiert',superseded:'Ersetzt'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isAdmin=()=>{try{return !!JSON.parse(localStorage.getItem(ACCESS_KEY)||'null')?.platform_admin}catch{return false}};
async function rpc(name,body={}){if(!API())throw new Error('API noch nicht bereit');return API().request(`/rest/v1/rpc/${name}`,{method:'POST',body})}
function markdown(data){const entries=data?.entries||[],groups=[['decision','Entscheidungen'],['roadmap','Roadmap'],['known_issue','Bekannte Punkte'],['release','Releases']];let out=`# ${data?.project||'Volleyball Trainer'} – Projektstand\n\nErzeugt: ${new Date(data?.generated_at||Date.now()).toLocaleString('de-DE')}\nAktuelle Version: ${data?.current_version||'–'}\n`;for(const [type,title] of groups){const rows=entries.filter(x=>x.entry_type===type);if(!rows.length)continue;out+=`\n## ${title}\n`;for(const x of rows){out+=`\n### ${x.title}\nStatus: ${labels[x.status]||x.status}${x.app_version?` · Version ${x.app_version}`:''}${x.commit_sha?` · Commit ${x.commit_sha}`:''}\n\n${x.content}\n`;if(x.tags?.length)out+=`\nTags: ${x.tags.join(', ')}\n`}}return out.trim()}
function section(){return `<section class="admin-section project-memory" id="projectMemoryPanel"><div class="project-memory-head"><div><h3>Projektgedächtnis</h3><p class="hint">Verbindliche Entscheidungen, Releases und nächste Schritte.</p></div><div class="project-memory-actions"><button type="button" data-project-action="copy">Übergabe kopieren</button><button type="button" class="primary" data-project-action="new">＋ Eintrag</button></div></div><p class="project-memory-status" aria-live="polite"></p><div class="project-memory-list"></div></section>`}
function form(entry=null){const overlay=document.createElement('div');overlay.className='project-memory-overlay';overlay.innerHTML=`<form class="project-memory-form"><div class="project-memory-form-head"><div><span class="eyebrow">${entry?'Neue Revision':'Neuer Eintrag'}</span><h2>Projektgedächtnis</h2></div><button type="button" data-close>✕</button></div><label>Art<select name="entry_type"><option value="decision">Entscheidung</option><option value="release">Release</option><option value="roadmap">Roadmap</option><option value="known_issue">Bekannter Punkt</option></select></label><label>Titel<input name="title" maxlength="180" required value="${esc(entry?.title||'')}"></label><label>Beschreibung<textarea name="content" rows="7" maxlength="12000" required>${esc(entry?.content||'')}</textarea></label><div class="project-memory-grid"><label>Status<select name="status"><option value="active">Aktiv</option><option value="planned">Geplant</option><option value="done">Erledigt</option><option value="accepted">Akzeptiert</option></select></label><label>App-Version<input name="app_version" maxlength="40" value="${esc(entry?.app_version||'')}"></label><label>Commit<input name="commit_sha" maxlength="80" value="${esc(entry?.commit_sha||'')}"></label><label>Tags, mit Komma getrennt<input name="tags" value="${esc((entry?.tags||[]).join(', '))}"></label></div><p class="project-memory-form-status" aria-live="polite"></p><div class="project-memory-form-actions"><button type="button" data-close>Abbrechen</button><button type="submit" class="primary">${entry?'Revision speichern':'Eintrag speichern'}</button></div></form>`;document.body.appendChild(overlay);overlay.querySelector('[name="entry_type"]').value=entry?.entry_type||'decision';overlay.querySelector('[name="status"]').value=entry?.status||'active';overlay.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>overlay.remove());overlay.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget),button=ev.currentTarget.querySelector('[type="submit"]'),status=overlay.querySelector('.project-memory-form-status');button.disabled=true;status.textContent='Wird gespeichert …';try{await rpc('save_project_log_entry',{p_entry_type:fd.get('entry_type'),p_title:fd.get('title').trim(),p_content:fd.get('content').trim(),p_status:fd.get('status'),p_app_version:fd.get('app_version').trim(),p_commit_sha:fd.get('commit_sha').trim(),p_tags:String(fd.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),p_replaces_id:entry?.id||null});overlay.remove();await render()}catch(e){status.textContent=`Speichern fehlgeschlagen: ${e.message}`}finally{button.disabled=false}}}
async function copyContext(status){const data=await rpc('get_project_context');const text=markdown(data);try{await navigator.clipboard.writeText(text);status.textContent='Projektübergabe wurde kopiert.'}catch(_){window.prompt('Projektübergabe kopieren:',text)}}
async function render(){const root=document.getElementById('projectMemoryPanel');if(!root||!isAdmin())return;const status=root.querySelector('.project-memory-status'),list=root.querySelector('.project-memory-list');status.textContent='Projektstand wird geladen …';try{const data=await rpc('get_project_context'),entries=data?.entries||[];list.innerHTML=entries.map(x=>`<article class="project-memory-card"><div><span class="project-memory-type">${esc(labels[x.entry_type]||x.entry_type)}</span><h4>${esc(x.title)}</h4><p>${esc(x.content)}</p><small>${esc(labels[x.status]||x.status)}${x.app_version?` · ${esc(x.app_version)}`:''}${x.tags?.length?` · ${esc(x.tags.join(', '))}`:''}</small></div><button type="button" data-project-edit="${x.id}">Neue Revision</button></article>`).join('')||'<p class="hint">Noch keine Einträge vorhanden.</p>';root._projectData=data;status.textContent=`${entries.length} aktuelle Einträge · Version ${data?.current_version||'–'}`}catch(e){status.textContent=`Projektstand konnte nicht geladen werden: ${e.message}`}}
function wire(root){root.querySelector('[data-project-action="new"]').onclick=()=>form();root.querySelector('[data-project-action="copy"]').onclick=async()=>{const s=root.querySelector('.project-memory-status');try{await copyContext(s)}catch(e){s.textContent=`Übergabe konnte nicht erstellt werden: ${e.message}`}};root.querySelector('.project-memory-list').onclick=e=>{const b=e.target.closest('[data-project-edit]');if(!b)return;const entry=(root._projectData?.entries||[]).find(x=>x.id===b.dataset.projectEdit);if(entry)form(entry)}}
let rendering=false;async function install(){if(rendering||!isAdmin())return false;const content=document.getElementById('platformAdminContent');if(!content||document.getElementById('projectMemoryPanel'))return Boolean(content);rendering=true;content.insertAdjacentHTML('beforeend',section());const root=document.getElementById('projectMemoryPanel');wire(root);await render();rendering=false;return true}
let booted=false;function boot(){if(booted)return true;const content=document.getElementById('platformAdminContent');if(!content)return false;booted=true;new MutationObserver(()=>{if(isAdmin()&&!document.getElementById('projectMemoryPanel'))install()}).observe(content,{childList:true});document.getElementById('platformAdminOpen')?.addEventListener('click',()=>setTimeout(install,120));document.getElementById('platformOnlyAdminOpen')?.addEventListener('click',()=>setTimeout(install,120));document.getElementById('platformAdminRefresh')?.addEventListener('click',()=>setTimeout(install,180));if(isAdmin())install();return true}
let tries=0,timer=setInterval(()=>{tries++;if(boot()||tries>80)clearInterval(timer)},250);boot();
})();
