const VERSION = "3.14.38";
const CORE_VERSION = "3.13.0";
const CACHE_PREFIX = "volleyball-trainer-shell-";
const CACHE_NAME = `${CACHE_PREFIX}${VERSION}`;
const OFFLINE_MUSIC_CACHE = "vb-training-music-v1";
const VOICE_ASSETS = ["kerstin","thorsten"].map(name => `./assets/audio/voice-de-${name}/voice.mp3`);
const CUSTOM_VOICE_ASSETS = ["b","c"].flatMap(pack => ["three","two","one","and","work","pause","action","continue","change","next-station"].map(name => `./assets/audio/voice-custom-${pack}/${name}.mp3`));
const APP_SHELL = ["./index.html",`./style.css?v=${CORE_VERSION}`,`./vendor/tone-15.1.22.js?v=${CORE_VERSION}`,`./music-library.js?v=${CORE_VERSION}`,`./training-player.js?v=${CORE_VERSION}`,`./app.js?v=${CORE_VERSION}`,`./config.js?v=${VERSION}`,`./exercise-library.css?v=${VERSION}`,`./exercise-library.js?v=${VERSION}`,`./feature-admin.js?v=${VERSION}`,`./ui-3.14.4.css?v=${VERSION}`,`./ui-3.14.12.css?v=${VERSION}`,`./ui-3.14.13.css?v=${VERSION}`,`./ui-3.14.14.css?v=${VERSION}`,`./ui-3.14.15.css?v=${VERSION}`,`./ui-3.14.16.css?v=${VERSION}`,`./ui-3.14.17.css?v=${VERSION}`,`./ui-3.14.18.css?v=${VERSION}`,`./ui-3.14.19.css?v=${VERSION}`,`./ui-3.14.20.css?v=${VERSION}`,`./ui-3.14.21.css?v=${VERSION}`,`./ui-3.14.22.css?v=${VERSION}`,`./ui-3.14.23.css?v=${VERSION}`,`./ui-3.14.24.css?v=${VERSION}`,`./ui-3.14.25.css?v=${VERSION}`,`./ui-3.14.26.css?v=${VERSION}`,`./ui-3.14.27.css?v=${VERSION}`,`./ui-3.14.28.css?v=${VERSION}`,`./ui-3.14.29.css?v=${VERSION}`,`./ui-3.14.36.css?v=${VERSION}`,`./manifest.webmanifest?v=${CORE_VERSION}`,`./assets/ttc-logo.png?v=${CORE_VERSION}`,`./assets/apple-touch-icon.png?v=${CORE_VERSION}`,`./assets/icon-192.png?v=${CORE_VERSION}`,`./assets/icon-512.png?v=${CORE_VERSION}`,"./assets/audio/kick.wav","./assets/audio/snare.wav","./assets/audio/hat-closed.wav","./assets/audio/hat-open.wav","./assets/audio/bass-c2.wav","./assets/audio/bass-c3.wav","./assets/audio/LICENSE.md","./assets/audio/voice-de-kerstin/LICENSE.md","./assets/audio/voice-de-thorsten/LICENSE.md","./assets/audio/voice-custom-b/README.md","./assets/audio/voice-custom-c/README.md","./assets/music/ronald-kah/LICENSE.md",...VOICE_ASSETS,...CUSTOM_VOICE_ASSETS];
const absoluteUrl=path=>new URL(path,self.registration.scope).href,INDEX_URL=absoluteUrl("./index.html"),VERSION_URL=absoluteUrl("./version.json"),APP_SHELL_URLS=new Set(APP_SHELL.map(absoluteUrl));
async function shellResponse(response){if(!response?.ok)return response;const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return response;let html=await response.text();html=html.replace(/<meta name="theme-color" content="[^"]*">/i,'<meta name="theme-color" content="#153b72">').replace(/<meta name="apple-mobile-web-app-status-bar-style" content="[^"]*">/i,'<meta name="apple-mobile-web-app-status-bar-style" content="black">');const headers=new Headers(response.headers);headers.delete("content-length");return new Response(html,{status:response.status,statusText:response.statusText,headers})}
self.addEventListener("message",event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener("install",event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);for(const path of APP_SHELL){try{const request=new Request(absoluteUrl(path),{cache:"reload"}),response=await fetch(request);if(response.ok)await cache.put(request,response)}catch(err){console.warn('App-Shell-Datei konnte nicht vorgeladen werden',path,err)}}await self.skipWaiting()})())});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE_NAME).map(key=>caches.delete(key)));await self.clients.claim()})())});
self.addEventListener("fetch",event=>{const request=event.request,url=new URL(request.url);if(request.method!=="GET"||url.origin!==self.location.origin)return;if(url.href===VERSION_URL||url.pathname.endsWith("/version.json")){event.respondWith(fetch(request,{cache:"no-store"}));return}if(url.pathname.endsWith("/config.js")||url.pathname.endsWith("/sw.js")){event.respondWith(fetch(request,{cache:"no-store"}).catch(()=>caches.match(request)));return}if(request.mode==="navigate"){event.respondWith((async()=>{try{const response=await fetch(request,{cache:"no-store"});if(response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(INDEX_URL,response.clone())}return shellResponse(response)}catch{const cached=await caches.match(INDEX_URL);return cached?shellResponse(cached):Response.error()}})());return}if(APP_SHELL_URLS.has(url.href)){event.respondWith((async()=>{const cached=await caches.match(request);const network=fetch(request,{cache:"no-cache"}).then(async response=>{if(response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(request,response.clone())}return response}).catch(()=>null);return cached||(await network)||Response.error()})());return}if(request.destination==="audio"||url.pathname.includes("/assets/music/")||url.pathname.includes("/assets/audio/")){event.respondWith((async()=>{const cache=await caches.open(OFFLINE_MUSIC_CACHE),cached=await cache.match(request);if(cached)return cached;try{const response=await fetch(request);if(response.ok)await cache.put(request,response.clone());return response}catch{return Response.error()}})())}});