const VERSION = "3.14.25";
const CORE_VERSION = "3.13.0";
const CACHE_PREFIX = "volleyball-trainer-shell-";
const CACHE_NAME = `${CACHE_PREFIX}${VERSION}`;
const OFFLINE_MUSIC_CACHE = "vb-training-music-v1";
const VOICE_ASSETS = ["kerstin","thorsten"].map(name => `./assets/audio/voice-de-${name}/voice.mp3`);
const CUSTOM_VOICE_ASSETS = ["b","c"].flatMap(pack => ["three","two","one","and","work","pause","action","continue","change","next-station"].map(name => `./assets/audio/voice-custom-${pack}/${name}.mp3`));
const APP_SHELL = ["./index.html",`./style.css?v=${CORE_VERSION}`,`./vendor/tone-15.1.22.js?v=${CORE_VERSION}`,`./music-library.js?v=${CORE_VERSION}`,`./training-player.js?v=${CORE_VERSION}`,`./app.js?v=${CORE_VERSION}`,`./config.js?v=${VERSION}`,`./exercise-library.css?v=${VERSION}`,`./exercise-library.js?v=${VERSION}`,`./feature-admin.js?v=${VERSION}`,`./ui-3.14.4.css?v=${VERSION}`,`./ui-3.14.12.css?v=${VERSION}`,`./ui-3.14.13.css?v=${VERSION}`,`./ui-3.14.14.css?v=${VERSION}`,`./ui-3.14.15.css?v=${VERSION}`,`./ui-3.14.16.css?v=${VERSION}`,`./ui-3.14.17.css?v=${VERSION}`,`./ui-3.14.18.css?v=${VERSION}`,`./ui-3.14.19.css?v=${VERSION}`,`./ui-3.14.20.css?v=${VERSION}`,`./ui-3.14.21.css?v=${VERSION}`,`./ui-3.14.22.css?v=${VERSION}`,`./ui-3.14.23.css?v=${VERSION}`,`./ui-3.14.24.css?v=${VERSION}`,`./ui-3.14.25.css?v=${VERSION}`,`./manifest.webmanifest?v=${CORE_VERSION}`,`./assets/ttc-logo.png?v=${CORE_VERSION}`,`./assets/apple-touch-icon.png?v=${CORE_VERSION}`,`./assets/icon-192.png?v=${CORE_VERSION}`,`./assets/icon-512.png?v=${CORE_VERSION}`,"./assets/audio/kick.wav","./assets/audio/snare.wav","./assets/audio/hat-closed.wav","./assets/audio/hat-open.wav","./assets/audio/bass-c2.wav","./assets/audio/bass-c3.wav","./assets/audio/LICENSE.md","./assets/audio/voice-de-kerstin/LICENSE.md","./assets/audio/voice-de-thorsten/LICENSE.md","./assets/audio/voice-custom-b/README.md","./assets/audio/voice-custom-c/README.md","./assets/music/ronald-kah/LICENSE.md",...VOICE_ASSETS,...CUSTOM_VOICE_ASSETS];
const absoluteUrl=path=>new URL(path,self.registration.scope).href,INDEX_URL=absoluteUrl("./index.html"),VERSION_URL=absoluteUrl("./version.json"),APP_SHELL_URLS=new Set(APP_SHELL.map(absoluteUrl));
async function iosShellResponse(response){if(!response?.ok)return response;const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return response;let html=await response.text();html=html.replace('name="apple-mobile-web-app-status-bar-style" content="default"','name="apple-mobile-web-app-status-bar-style" content="black-translucent"').replace('name="theme-color" content="#0b4fc6"','name="theme-color" content="#153b72"');if(!html.includes('ui-3.14.24.css'))html=html.replace('</head>',`  <link rel="stylesheet" href="ui-3.14.24.css?v=${VERSION}">\n</head>`);if(!html.includes('ui-3.14.25.css'))html=html.replace('</head>',`  <link rel="stylesheet" href="ui-3.14.25.css?v=${VERSION}">\n</head>`);if(!html.includes('vb-ios-theme-sync'))html=html.replace('</body>',`<script id="vb-ios-theme-sync">(()=>{const m=document.querySelector('meta[name="theme-color"]');if(!m)return;const sync=()=>m.setAttribute('content',document.body.classList.contains('editing-mode')?'#f5d04c':'#153b72');sync();new MutationObserver(sync).observe(document.body,{attributes:true,attributeFilter:['class']})})()</script>\n</body>`);if(!html.includes('vb-public-feature-version'))html=html.replace('</body>',`<script id="vb-public-feature-version">window.addEventListener('load',()=>{requestAnimationFrame(()=>{const e=document.getElementById('brandVersion');if(e){e.textContent='3.14.25';e.setAttribute('aria-label','Version 3.14.25')}})})</script>\n</body>`);const headers=new Headers(response.headers);headers.delete("content-length");return new Response(html,{status:response.status,statusText:response.statusText,headers})}
self.addEventListener("install",event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);await Promise.all(APP_SHELL.map(async path=>{const request=new Request(absoluteUrl(path),{cache:"reload"}),response=await fetch(request);if(!response.ok)throw new Error(`App-Datei konnte nicht geladen werden: ${path}`);const stored=path==="./index.html"?await iosShellResponse(response):response;await cache.put(request,stored)}));await self.skipWaiting()})())});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE_NAME).map(key=>caches.delete(key)));await self.clients.claim()})())});
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;const configPath=new URL(absoluteUrl("./config.js")).pathname;if(url.pathname===new URL(VERSION_URL).pathname){event.respondWith(fetch(request,{cache:"no-store"}));return}if(url.pathname===configPath){event.respondWith((async()=>{try{const response=await fetch(request,{cache:"no-store"});if(response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(request,response.clone())}return response}catch{return(await caches.match(request))||Response.error()}})());return}if(request.mode==="navigate"){event.respondWith((async()=>{try{const network=await fetch(request,{cache:"no-store"});const response=await iosShellResponse(network);if(response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(INDEX_URL,response.clone())}return response}catch{return(await caches.match(INDEX_URL))||Response.error()}})());return}if(url.pathname.includes("/assets/music/ronald-kah/chunks/")&&url.pathname.endsWith(".mp3")){event.respondWith((async()=>{const cache=await caches.open(OFFLINE_MUSIC_CACHE);return(await cache.match(request))||fetch(request)})());return}if(!APP_SHELL_URLS.has(url.href))return;event.respondWith((async()=>{const cached=await caches.match(request);if(cached)return cached;return fetch(request,{cache:"no-store"})})())});